### ISSUE TITLE
Italic and Bold Italic install issues

### ISSUE THREAD

**Issue by mfm2453** [jonathonf/solbera-dnd-fonts#1]
Hello,
I've just recently gotten into writing up homebrew content and was trying to install the fonts but the Bookinsanity Italic and Bold Italic won't install on Windows 10. It keeps saying that they're not valid fonts.

**Comment by jonathonf** [comment]
That was raised last year on Ryrok's thread: https://www.reddit.com/r/UnearthedArcana/comments/4loka0/fixed_versions_of_solberas_fonts/daa9fxh/

It may be possible to fix them using FontForge.

**Comment by jonathonf** [comment]
Can you check now with David's update https://github.com/jonathonf/solbera-dnd-fonts/pull/2/commits/51d29b1419e38102f12c15999f68dce0db696ca6 ?

**Comment by Payden-Pringle** [comment]
@jonathonf Bookinsanity and Bookinsanity-Bold install just fine. Bookinsanity-Italic and Bookinsanity-BoldItalic both still have this issue. I notice that the two working fonts have the "Fixed Mac Metadata" comment, while the two non-working fonts don't.

**Comment by jonathonf** [comment]
If you open a PR I can merge the fix.

**Comment by apastuszak** [comment]
@Payden-Pringle can you provice your font files somewhere for download.  I tried to do the same thing you did, and FontForge threw a bunch of errors.

**Comment by Krakaton** [comment]
I think I may have an idea as to why re-generating the font pack through FontForge tends to cause the issue with kerning. A colleague of mine was having letters overlapping and spacing poorly after re-generating the italic fonts. Upon opening the italic pack in FF, it gave a series of errors indicating all of the capital letters having the wrong Unicode values. I think FF is taking the glyphs, moving them to the values they're supposed to have, but only doing so for the contour lines. It seems that any kerning and extrema once present are lost in this process, meaning I'll have to see if I can do so manually.
There's also the fact that italic font packs are a separate entity from basic font packs. It may be that these were exported as italic font packs, and that the OTF file type is either having trouble recognizing them.
This also may be the reason the error message pops up for capital letters. I believe FF may use different Unicode values for capital letters depending on whether or not the font pack is italic.
Not entirely sure what I can do to fix this, if anything, but if this provides any insight to anyone else, then maybe we'll be one step closer to fixing this.

**Comment by PriamX** [comment]
I am experiencing this issue too, Windows 10 (1703)

**Comment by jonathonf** [comment]
Should be fixed by https://github.com/jonathonf/solbera-dnd-fonts/commit/5106cf8e3023a74dac487dfa94bdfc9225aa1973
