### ISSUE TITLE
Do you allow PR with font related to 5e settings?

### ISSUE THREAD

**Issue by lucastucious** [jonathonf/solbera-dnd-fonts#15]
Hi ! 
I do a lot of homebrew for 5e related content, but for a game called [Fateforge](https://fateforge.org/en), a setting and additional rules (imo far better than vanilla 5e).

The creator of this settings have shared the fonts used in their books, so the question is : can i PR a folder with theses ?

**Comment by jonathonf** [comment]
If the fonts are useful for homebrew then I don't see why not.

**Comment by lucastucious** [comment]
[Made a Pull request ! ](https://github.com/jonathonf/solbera-dnd-fonts/pull/17)

**Comment by lucastucious** [comment]
proper PR is #20 ;)
