### ISSUE TITLE
Font won't install on Windows 10

### ISSUE THREAD

**Issue by chris-velox** [jonathonf/solbera-dnd-fonts#4]
Windows 10 claims this file isn't a valid font file. I tried running it through a converter to .ttf, but that doesn't work. Typing letters yields small boxes in MS Word.

**Comment by jonathonf** [comment]
This sounds like a duplicate of the other issue: https://github.com/jonathonf/solbera-dnd-fonts/issues/1

Can you confirm whether it's the same thing? If it's not, can you detail why?

**Comment by chris-velox** [comment]
This does sound like a duplicate. My apologies.
