### ISSUE TITLE
Kerning on j is strange in Scaly sans

### ISSUE THREAD

**Issue by ryceg** [jonathonf/solbera-dnd-fonts#6]
Hi there,

Have an issue with the kerning of j being a little weird. This is on my webapp, Eigengrau's Generator. Unsure if it's on other sources as well.

![image](https://user-images.githubusercontent.com/36913739/95928990-880fcd00-0e0e-11eb-9089-cab00633e7c5.png)

**Comment by Gazook89** [comment]
Older issue, but came across it and checked it out on my computer:   Issue isn't Scaly Sans, it is Bookinsanity.   And yes, same issue:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/58999374/107606071-9aeab080-6bfa-11eb-96da-54727b4d945d.png">

**Comment by Gazook89** [comment]
@ryceg yo --- again, you may have moved well past any need for a correction on the 'j' on Bookinsanity, but I took it as an easy first project in FontForge and corrected the spacing.  Plus, I took the bad kerning on the J as personal insult, with a name like John J...Here is the revised font: https://github.com/Gazook89/solbera-dnd-fonts/blob/master/Bookinsanity/Bookinsanity.otf

<img width="225" alt="image" src="https://user-images.githubusercontent.com/58999374/107610105-74327700-6c06-11eb-911b-f5cae201b241.png">


I also screwed with the lowercase 'w' as that seemed a little goofy as well.  The uppercase 'W' is bad as well, but was a little harder to fix and it's not so bad (though now that I have mentioned it, it might drive you nuts).

If this helps you, I'll be happy to say I made an extremely tiny impact on Eigengrau!

**Comment by Gazook89** [comment]
Actually, better resource is these remade fonts found in this reddit thread: https://www.reddit.com/r/UnearthedArcana/comments/71wzc2/new_indesign_template_and_open_source_fonts/

It has complete latin character sets, corrected kerning for all characters, and some extra symbols.  For all of the standard dnd PHB fonts.  Contained in a single zip file, all .otf fonts.

**Comment by jonathonf** [comment]
Awesomesauce. I'll check these over then push the updated versions "soon".

**Comment by jonathonf** [comment]
Should be fixed by https://github.com/jonathonf/solbera-dnd-fonts/commit/5106cf8e3023a74dac487dfa94bdfc9225aa1973
